apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: monitoring
  name: monitoring
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
  selector:
    io.kompose.service: monitoring
status:
  loadBalancer: {}
