apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: monitoring
  name: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: monitoring
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: monitoring
    spec:
      containers:
      - image: microservices-monitoring
        imagePullPolicy: Never
        name: monitoring
        ports:
        - containerPort: 5002
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
