apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim1
  labels:
    io.kompose.service: nginx-claim1
spec:
  accessModes:
    - ReadWriteOnce  # Modification ici (ROX → RWO)
  resources:
    requests:
      storage: 100Mi
  storageClassName: "manual"  # Ajouté pour matcher les PVs