apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "manual"  # Ajouté pour matcher les PVCs
  hostPath:
    path: "/mnt/data/nginx0"
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "manual"  # Ajouté pour matcher les PVCs
  hostPath:
    path: "/mnt/data/nginx1"
  persistentVolumeReclaimPolicy: Retain