apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    io.kompose.service: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: postgres
  clusterIP: None  # Permet aux autres pods de se connecter via DNS interne