apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: signing
  name: signing
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: signing
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: signing
    spec:
      containers:
      - env:
        - name: POSTGRES_URI
          value: postgresql://admin:1234@postgres.default.svc.cluster.local/device_db
        - name: SIGNING_WORKERS
          value: "4"
        image: microservices-signing
        imagePullPolicy: Never
        name: signing
        ports:
        - containerPort: 5003
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
